{% set name = "lmz" %}
{% set version = "0.1.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lmz-{{ version }}.tar.gz
  sha256: 7022b57abe86da2d36b80c144edc1858fd355d293315bcd0674135a1f673a317

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - lmz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smautner/listmapzip
  summary: return lists
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smautner
