{% set name = "lmz" %}
{% set version = "0.1.19" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lmz-{{ version }}.tar.gz
  sha256: 1448d73692bb3e34bf4e1e36db74f82f1531ed3132ce92195dc9d0b2e9588de0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - lmz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smautner/listmapzip
  summary: return lists
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smautner
