{% set name = "lmz" %}
{% set version = "0.1.20" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lmz-{{ version }}.tar.gz
  sha256: a00703578789fde3073836f9df7a2724713f42abd02e606339d7de8f1f433741

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - lmz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smautner/listmapzip
  summary: return lists
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smautner
